import { useState } from "react";

export default function Home() {
  const path = `${import.meta.env.BASE_URL}`;

  const viteLogo = path + 'vite.webp';
  const htmlLogo = path + 'HTML5.webp';
  const cssLogo = path + 'CSS3.webp';
  const jsLogo = path + 'JS.webp';
  const tsLogo = path + 'TS.webp';
  const reactLogo = path + 'react.webp';
  const linkedinLogo = path + 'linkedin.webp';
  const githubLogo = path + 'github.webp';

  const [value, setValue] = useState('');

  const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    const textarea = event.target;
    setValue(textarea.value);

    textarea.style.height = 'auto';
    textarea.style.height = textarea.scrollHeight + 'px';
  }

  return (
    <main>
      <h1
        className="
          text-5xl 
          leading-loose"
      >
        Bonjour, je suis Eric
      </h1>
      <h2
        className="
        pt-12
        text-4xl
        leading-loose"
      >
        votre intégrateur web React en Île-de-France
      </h2>
      <section>
        <h3
          className="
          pt-10
          text-3xl
          leading-loose"
        >À propos de moi</h3>
        Développez votre activité en évitant les 
        <span 
          className="
          mx-2 
          font-extrabold"
        >
          frictions.
        </span> 
        Améliorez vos 
        <span
          className="
            mx-2 
            font-extrabold"
        >
          chiffres 
        </span>
        clés de 
        <span 
          className="
            mx-2 
            font-extrabold
            text-violet-600"
        >
          performances.
        </span> 
        Passionné par les sites web, les interfaces 
        <span 
          className="
            mx-2 
            font-extrabold 
            text-green-600"
        >
          durables
        </span>
        que j'intègre simplifient l'utilisation par tou·te·s. 
      </section>
      <section>
        <h3
          className="
          pt-10 
          text-3xl
          leading-loose"
        >compétences</h3>
        <div className="
          flex
          justify-center
          flex-wrap"
        >
          <img 
            src={viteLogo} 
            className='
              lazy 
              p-6 
              h-25
              will-change-filter 
              filter 
              duration-300
              hover:drop-shadow-[0_0_2em_#646cffaa]' 
            alt='Vite logo' />
          <img 
            src={htmlLogo} 
            className='
              lazy 
              p-6 
              h-25 
              will-change-filter 
              filter 
              duration-300
              hover:drop-shadow-[0_0_2em_#646cffaa]' 
            alt='HTML5 logo' />
          <img 
            src={cssLogo} 
            className='
              lazy 
              p-6 
              h-25 
              will-change-filter 
              filter 
              duration-300
              hover:drop-shadow-[0_0_2em_#646cffaa]' 
            alt='CSS3 logo' />      
          <img 
            src={jsLogo} 
            className='
              lazy 
              p-6 
              h-25 
              will-change-filter 
              filter 
              duration-300
              hover:drop-shadow-[0_0_2em_#646cffaa]' 
            alt='JavaScript logo' />
          <img 
            src={tsLogo} 
            className=' 
              lazy 
              p-6 
              h-25 
              will-change-filter 
              filter 
              duration-300
              hover:drop-shadow-[0_0_2em_#646cffaa]' 
            alt='TypeScript logo' />
          <img 
            src={reactLogo} 
            className='
              lazy 
              p-6 
              h-25 
              will-change-filter 
              filter 
              duration-300
              hover:drop-shadow-[0_0_2em_#61dafbaa]
              animate-[spin_20s_linear_infinite]' 
            alt='React logo' />
          </div>
        </section>
        <section>
          <h3
            className="
              pt-10
              text-3xl
              leading-loose"
          >
            projets
          </h3>
          <h4
            className="
              text-2xl
              leading-loose"
          >
            Riding cities, découvrez le skateboard près de chez vous.
          </h4>
          <a
            href="https://ericdev1o.github.io/OC900_p2_RidingCities/"
            target="_blank"
            className="text-orange-600"
          >
            p2 Riding Cities
          </a>
          <h4
            className="
              text-2xl
              leading-loose"
          >
            Booki, votre agence de voyage
          </h4>
          <a 
            href="https://ericdev1o.github.io/OC900_p3_Booki/"
            target="_blank"
            className="
              text-orange-600"
          >
            p3 Booki
          </a>
      </section>
      <section>
        <h3
          className="
            pt-10 
            text-3xl
            leading-loose"
        >parcours</h3>
        <p>
          22 avril 2024 à aujourd'hui : 
          <span
            className="
              mx-2
              font-extrabold
              text-violet-600"
            >
              intégrateur web 
          </span>
          RNCP 38145
          <a 
            href="https://openclassrooms.com/fr/paths/900-integrateur-web#projects"
            target="_blank"
            className="
              mx-2 
              font-medium 
              text-fg-brand 
              hover:underline"
          >
            suivez le parcours
          </a>
        </p>
        <p>
          Contribuons 
          <span
            className="
              mx-2
              font-extrabold
              text-green-600"
          >
            doucement 
          </span>
          à votre 
          <span
            className="
              mx-2
              font-extrabold
              text-gray-600"
          >
            projet
          </span> 
          web avec 
          <span
            className="
              mx-2
              font-extrabold
              text-green-600"
          >
            impact.
          </span>
        </p>
      </section>
      <section>
        <h3
          className="
            pt-10 
            text-3xl
            leading-loose"
        >
          contact
        </h3>
        <div 
          className="
            flex
            justify-center"
        >
          <a 
            href='https://github.com/ericDev1o' 
            target='_blank'
          >
            <img 
              src={githubLogo} 
              className='
                p-6 
                h-25 
                will-change-filter 
                filter 
                duration-300
                hover:drop-shadow-[0_0_2em_#646cffaa]' 
              alt='GitHub logo' />
          </a>
          <a 
            href='https://linkedin.com/in/ericfaraut' 
            target='_blank'
          >
            <img 
              src={linkedinLogo} 
              className='
                p-6 
                h-25 
                will-change-filter 
                filter 
                duration-300
                hover:drop-shadow-[0_0_2em_#646cffaa]' 
              alt='LinkedIn logo' />
          </a>
        </div>
        <h4
          className="
            pt-8 
            text-2xl
            leading-loose"
        >
          Utilisez s'il-vous-plaît provisoirement le formulaire Framaform ci-dessous pour une meilleure confidentialité des courriels.
        </h4>
        <a 
          href="https://framaforms.org/contact-eric-faraut-1762791991"
          target='_blank'
        >
          <button 
              className="
                mt-4 
                text-gray-700 
                bg-orange-600 
                hover:bg-orange-700
                cursor-pointer 
                focus:ring-4 
                focus:outline-none 
                focus:ring-blue-300 
                font-medium 
                rounded-lg 
                text-sm 
                w-full 
                sm:w-auto 
                px-5 
                py-2.5 
                text-center"
            >
              Parlons de votre projet de site web
            </button>
          </a>
        <form 
          className="
            max-w-md 
            mx-auto
            pt-12"
        >
          <div 
          className="
            relative
            z-0 
            w-full 
            mb-5 
            group"
          >
            <input 
              type="email" 
              name="floating_email" 
              id="floating_email" 
              className="
                disabled: cursor-not-allowed
                block 
                py-2.5 
                px-0 
                w-full 
                text-sm 
                text-gray-900 
                bg-transparent 
                border-0 
                border-b-2 
                border-gray-300 
                appearance-none 
                dark:text-white 
                dark:border-gray-600 
                dark:focus:border-blue-500 
                focus:outline-none 
                focus:ring-0 
                focus:border-blue-600 
                peer" 
                placeholder=" " 
                required 
            />
            <label 
              htmlFor="floating_email" 
              className=" 
                peer-focus:font-medium 
                absolute 
                w-full 
                text-sm 
                text-gray-500 
                dark:text-gray-400 
                duration-300 
                transform 
                -translate-y-6 
                scale-75 
                top-3 
                right-32
                -z-10 
                origin-left 
                peer-focus:start-0 
                rtl:peer-focus:translate-x-1/4 
                rtl:peer-focus:left-auto 
                peer-focus:text-blue-600 
                peer-focus:dark:text-blue-500 
                peer-placeholder-shown:scale-100 
                peer-placeholder-shown:translate-y-0 
                peer-focus:scale-75 
                peer-focus:-translate-y-6"
            >
              courriel (obligatoire)
            </label>
            <p 
              className="
                mt-2 
                text-sm 
                text-red-700 
                dark:text-red-800"
            >
              Veuillez cliquer sur le bouton 
               <span 
                className="
                  mx-2 
                  font-extrabold
                  text-orange-700"
              >
                orange 
              </span>
              ci-dessus
              <span
                className="
                  mx-2 
                  font-extrabold"
              >plutôt 
              </span>
              que le
              <span
                className="
                  mx-2 
                  font-extrabold
                  text-blue-600"
              >
                bleu 
              </span>
              ci-dessous s'il vous plaît. 
            </p>
          </div>
          <div 
            className="
              relative 
              z-0 
              w-full 
              mb-5 
              group"
          >
            <input 
              type="text" 
              name="floating_first_name" 
              id="floating_first_name" 
              className="
                disabled: cursor-not-allowed
                block 
                py-2.5 
                px-0 
                w-full 
                text-sm 
                text-gray-900 
                bg-transparent 
                border-0 
                border-b-2 
                border-gray-300 
                appearance-none 
                dark:text-white 
                dark:border-gray-600 
                dark:focus:border-blue-500 
                focus:outline-none
                focus:ring-0
                focus:border-blue-600
                peer" 
                placeholder=" " 
                required 
            />
            <label 
              htmlFor="floating_first_name" 
              className="
                peer-focus:font-medium 
                absolute 
                w-full 
                text-sm 
                text-gray-500 
                dark:text-gray-400 
                duration-300 
                transform 
                -translate-y-6 
                scale-75 
                top-3 
                right-34 
                -z-10 
                origin-left 
                peer-focus:start-0 
                rtl:peer-focus:translate-x-1/4 
                peer-focus:text-blue-600 
                peer-focus:dark:text-blue-500 
                peer-placeholder-shown:scale-100 
                peer-placeholder-shown:translate-y-0 
                peer-focus:scale-75 
                peer-focus:-translate-y-6"
            >
              Prénom (obligatoire)
            </label>
          </div>
          <div 
            className="
              relative 
              z-0 
              w-full 
              mb-5 
              group"
          >
            <input 
              type="text" 
              name="floating_last_name" 
              id="floating_last_name" 
              className="
                disabled: cursor-not-allowed
                block 
                py-2.5 
                px-0 
                w-full 
                text-sm 
                text-gray-900 
                bg-transparent 
                border-0 
                border-b-2 
                border-gray-300 
                appearance-none 
                dark:text-white 
                dark:border-gray-600 
                dark:focus:border-blue-500 
                focus:outline-none 
                focus:ring-0 
                focus:border-blue-600 
                peer" 
              placeholder=" " 
              required 
            />
            <label 
              htmlFor="floating_last_name" 
              className="
                peer-focus:font-medium 
                absolute 
                w-full 
                text-sm 
                text-gray-500 
                dark:text-gray-400 
                duration-300 
                transform 
                -translate-y-6 
                scale-75 
                top-3 
                right-37 
                -z-10 
                origin-left 
                peer-focus:start-0 
                rtl:peer-focus:translate-x-1/4 
                peer-focus:text-blue-600 
                peer-focus:dark:text-blue-500 
                peer-placeholder-shown:scale-100 
                peer-placeholder-shown:translate-y-0 
                peer-focus:scale-75 
                peer-focus:-translate-y-6"
            >
              Nom (obligatoire)
            </label>
          </div>
          <div 
            className="
              relative 
              z-0 
              w-full 
              mb-5 
              group"
          >
            <input 
              type="tel" 
              pattern="+33 [1-9]{1} [0-9]{2} [0-9]{2} [0-9]{2} [0-9]{2}" 
              name="floating_phone" 
              id="floating_phone" 
              className="
                disabled: cursor-not-allowed
                block 
                py-2.5 
                px-0 
                w-full 
                text-sm 
                text-gray-900 
                bg-transparent 
                border-0 
                border-b-2 
                border-gray-300 
                appearance-none 
                dark:text-white 
                dark:border-gray-600 
                dark:focus:border-blue-500 
                focus:outline-none 
                focus:ring-0 
                focus:border-blue-600 
                peer" 
                placeholder=" " 
              />
            <label 
              htmlFor="floating_phone" 
              className="
                peer-focus:font-medium 
                absolute 
                text-sm 
                text-gray-500 
                dark:text-gray-400 
                duration-300 
                transform 
                -translate-y-6 
                scale-75 
                top-3 
                right-50.5 
                -z-10 
                origin-left 
                peer-focus:start-0 
                rtl:peer-focus:translate-x-1/4 
                peer-focus:text-blue-600 
                peer-focus:dark:text-blue-500 
                peer-placeholder-shown:scale-100 
                peer-placeholder-shown:translate-y-0 
                peer-focus:scale-75 
                peer-focus:-translate-y-6
                "
            >
              téléphone (+33 1 23 45 67 89)
            </label>
          </div>
          <div 
            className="
              relative 
              z-0 
              w-full 
              mb-5 
              group"
          >
            <input 
              type="text" 
              name="floating_company" 
              id="floating_company" 
              className="
                disabled: cursor-not-allowed
                block 
                py-2.5 
                px-0 
                w-full 
                text-sm 
                text-gray-900 
                bg-transparent 
                border-0 
                border-b-2 
                border-gray-300 
                appearance-none 
                dark:text-white 
                dark:border-gray-600 
                dark:focus:border-blue-500 
                focus:outline-none 
                focus:ring-0 
                focus:border-blue-600 
                peer" 
              placeholder=" "
            />
            <label 
              htmlFor="floating_company" 
              className="
                peer-focus:font-medium 
                absolute 
                w-full 
                text-sm 
                text-gray-500 
                dark:text-gray-400 
                duration-300 
                transform 
                -translate-y-6 
                scale-75 
                top-3 
                right-48 
                -z-10 
                origin-left 
                peer-focus:start-0 
                rtl:peer-focus:translate-x-1/4 
                peer-focus:text-blue-600 
                peer-focus:dark:text-blue-500 
                peer-placeholder-shown:scale-100 
                peer-placeholder-shown:translate-y-0 
                peer-focus:scale-75 
                peer-focus:-translate-y-6"
            >
              Société
            </label>
          </div>
          <div 
            className="
              relative 
              z-0 
              w-full 
              mb-5 
              group"
          >
            <label 
              htmlFor="message" 
              className="
                block 
                mb-2 
                text-sm 
                font-medium 
                text-gray-900 
                dark:text-white"
            >
              Parlons de votre projet de site web
            </label>
            <textarea 
              id="message"
              value={value}
              onChange={handleChange} 
              className="
                disabled: cursor-not-allowed
                block 
                p-2.5 
                min-h-24 
                w-full 
                text-sm 
                text-gray-900 
                bg-gray-50 
                rounded-lg 
                border 
                border-gray-300 
                focus:ring-blue-500 
                focus:border-blue-500 
                dark:bg-gray-700 
                dark:border-gray-600 
                dark:placeholder-gray-400 
                dark:text-white 
                dark:focus:ring-blue-500 
                dark:focus:border-blue-500" 
              placeholder="Veuillez s'il-vous-plaît avoir la patience de cliquer sur le bouton orange ci-dessus."
            >
            </textarea>
            <p 
              className="
                mt-2 
                text-sm 
                text-red-600 
                dark:text-red-500"
            >
              <span 
                className="font-medium"
              >Excusez-moi ne remplissez pas encore cet aperçu s'il vous plaît.
              </span>
               Veuillez cliquer sur le bouton orange ci-dessus plutôt que le bleu ci-dessous.
            </p>
          </div>
          <button 
            type="submit" 
            className="
              disabled: cursor-not-allowed 
              opacity-50 
              text-white 
              bg-blue-700 
              hover:bg-blue-800 
              focus:ring-4 
              focus:outline-none 
              focus:ring-blue-300 
              font-medium 
              rounded-lg 
              text-sm 
              w-full 
              sm:w-auto 
              px-5 
              py-2.5 
              text-center 
              dark:bg-blue-600 
              dark:hover:bg-blue-700 
              dark:focus:ring-blue-800"
          >
            Envoyer
          </button>
        </form>
     </section>
    </main>
  );
}
