import { useState } from "react";

export default function Form() {
  const [value, setValue] = useState('');

    const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    const textarea = event.target;
    setValue(textarea.value);

    textarea.style.height = 'auto';
    textarea.style.height = textarea.scrollHeight + 'px';
  }
  return <form 
        className="
          max-w-md 
          mx-auto
          pt-12"
      >
        <div 
        className="
          relative
          z-0 
          w-full 
          mb-5 
          group"
        >
          <input 
            type="email" 
            name="floating_email" 
            id="floating_email" 
            className="
              disabled: cursor-not-allowed
              block 
              py-2.5 
              px-0 
              w-full 
              text-sm 
              text-gray-900 
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-300 
              appearance-none 
              dark:text-white 
              dark:border-gray-600 
              dark:focus:border-blue-500 
              focus:outline-none 
              focus:ring-0 
              focus:border-blue-600 
              peer" 
              placeholder=" " 
              required 
          />
          <label 
            htmlFor="floating_email" 
            className=" 
              peer-focus:font-medium 
              absolute 
              w-full 
              text-sm 
              text-gray-500 
              dark:text-gray-400 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              top-3 
              right-32
              -z-10 
              origin-left 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              rtl:peer-focus:left-auto 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6"
          >
            courriel (obligatoire)
          </label>
          <p 
            className="
              mt-2 
              text-sm 
              text-red-700 
              dark:text-red-800"
          >
            Veuillez cliquer sur le bouton 
              <span 
              className="
                mx-2 
                font-extrabold
                text-blue-500"
            >
              bleu 
            </span>
            ci-dessus
            <span
              className="
                mx-2 
                font-extrabold"
            >plutôt 
            </span>
            que le
            <span
              className="
                mx-2 
                font-extrabold
                text-blue-600"
            >
              bleu 
            </span>
            ci-dessous s'il vous plaît. 
          </p>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <input 
            type="text" 
            name="floating_first_name" 
            id="floating_first_name" 
            className="
              disabled: cursor-not-allowed
              block 
              py-2.5 
              px-0 
              w-full 
              text-sm 
              text-gray-900 
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-300 
              appearance-none 
              dark:text-white 
              dark:border-gray-600 
              dark:focus:border-blue-500 
              focus:outline-none
              focus:ring-0
              focus:border-blue-600
              peer" 
              placeholder=" " 
              required 
          />
          <label 
            htmlFor="floating_first_name" 
            className="
              peer-focus:font-medium 
              absolute 
              w-full 
              text-sm 
              text-gray-500 
              dark:text-gray-400 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              top-3 
              right-34 
              -z-10 
              origin-left 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6"
          >
            Prénom (obligatoire)
          </label>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <input 
            type="text" 
            name="floating_last_name" 
            id="floating_last_name" 
            className="
              disabled: cursor-not-allowed
              block 
              py-2.5 
              px-0 
              w-full 
              text-sm 
              text-gray-900 
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-300 
              appearance-none 
              dark:text-white 
              dark:border-gray-600 
              dark:focus:border-blue-500 
              focus:outline-none 
              focus:ring-0 
              focus:border-blue-600 
              peer" 
            placeholder=" " 
            required 
          />
          <label 
            htmlFor="floating_last_name" 
            className="
              peer-focus:font-medium 
              absolute 
              w-full 
              text-sm 
              text-gray-500 
              dark:text-gray-400 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              top-3 
              right-37 
              -z-10 
              origin-left 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6"
          >
            Nom (obligatoire)
          </label>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <input 
            type="tel" 
            pattern="+33 [1-9]{1} [0-9]{2} [0-9]{2} [0-9]{2} [0-9]{2}" 
            name="floating_phone" 
            id="floating_phone" 
            className="
              disabled: cursor-not-allowed
              block 
              py-2.5 
              px-0 
              w-full 
              text-sm 
              text-gray-900 
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-300 
              appearance-none 
              dark:text-white 
              dark:border-gray-600 
              dark:focus:border-blue-500 
              focus:outline-none 
              focus:ring-0 
              focus:border-blue-600 
              peer" 
              placeholder=" " 
            />
          <label 
            htmlFor="floating_phone" 
            className="
              peer-focus:font-medium 
              absolute 
              text-sm 
              text-gray-500 
              dark:text-gray-400 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              top-3 
              right-50.5 
              -z-10 
              origin-left 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6
              "
          >
            téléphone (+33 1 23 45 67 89)
          </label>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <input 
            type="text" 
            name="floating_company" 
            id="floating_company" 
            className="
              disabled: cursor-not-allowed
              block 
              py-2.5 
              px-0 
              w-full 
              text-sm 
              text-gray-900 
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-300 
              appearance-none 
              dark:text-white 
              dark:border-gray-600 
              dark:focus:border-blue-500 
              focus:outline-none 
              focus:ring-0 
              focus:border-blue-600 
              peer" 
            placeholder=" "
          />
          <label 
            htmlFor="floating_company" 
            className="
              peer-focus:font-medium 
              absolute 
              w-full 
              text-sm 
              text-gray-500 
              dark:text-gray-400 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              top-3 
              right-48 
              -z-10 
              origin-left 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6"
          >
            Société
          </label>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <label 
            htmlFor="message" 
            className="
              block 
              mb-2 
              text-sm 
              font-medium 
              text-gray-900 
              dark:text-white"
          >
            Parlons de votre projet de site web
          </label>
          <textarea 
            id="message"
            value={value}
            onChange={handleChange} 
            className="
              disabled: cursor-not-allowed
              block 
              p-2.5 
              min-h-24 
              w-full 
              text-sm 
              text-gray-900 
              bg-gray-50 
              rounded-lg 
              border 
              border-gray-300 
              focus:ring-blue-500 
              focus:border-blue-500 
              dark:bg-gray-700 
              dark:border-gray-600 
              dark:placeholder-gray-400 
              dark:text-white 
              dark:focus:ring-blue-500 
              dark:focus:border-blue-500" 
            placeholder="Veuillez s'il-vous-plaît avoir la patience de cliquer sur le bouton orange ci-dessus."
          >
          </textarea>
          <p 
            className="
              mt-2 
              text-sm 
              text-red-600 
              dark:text-red-500"
          >
            <span 
              className="font-medium"
            >Excusez-moi ne remplissez pas encore s'il vous plaît.
            </span>
              Veuillez cliquer sur le bouton orange ci-dessus plutôt que le bleu ci-dessous.
          </p>
        </div>
        <button 
          type="submit" 
          className="
            disabled: cursor-not-allowed 
            opacity-50 
            text-white 
            bg-blue-700 
            hover:bg-blue-800 
            focus:ring-4 
            focus:outline-none 
            focus:ring-blue-300 
            font-medium 
            rounded-lg 
            text-sm 
            w-full 
            sm:w-auto 
            px-5 
            py-2.5 
            text-center 
            dark:bg-blue-600 
            dark:hover:bg-blue-700 
            dark:focus:ring-blue-800"
        >
          Envoyer
        </button>
      </form>
}