import { useState } from "react";

export default function Form() {
  const [value, setValue] = useState('');

    const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    const textarea = event.target;
    setValue(textarea.value);

    textarea.style.height = 'auto';
    textarea.style.height = textarea.scrollHeight + 'px';
  }
  return <form 
        className="
          max-w-md 
          mx-auto
          pt-12"
      >
        <div 
        className="
          relative
          z-0 
          w-full 
          mb-5 
          group"
        >
          <input 
            type="email" 
            name="floating_email" 
            id="floating_email" 
            className="
              block 
              py-2.5 
              px-0 
              w-full 
              text-xl 
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-600 
              text-white 
              focus:border-blue-500 
              focus:outline-none 
              focus:ring-0 
              peer" 
              placeholder=" " 
              required 
          />
          <label 
            htmlFor="floating_email" 
            className=" 
              absolute 
              top-3 
              right-14
              -z-10 
              origin-left 
              w-full 
              text-xl 
              text-gray-300 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              peer-focus:font-medium 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              rtl:peer-focus:left-auto 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6"
          >
            courriel (a@b.c obligatoire)
          </label>
          <p 
            className="
              mt-2 
              text-sm 
              text-red-400"
          >
            Veuillez cliquer sur le bouton 
              <span 
              className="
                mx-2 
                font-extrabold
                text-blue-400"
            >
              bleu 
            </span>
            ci-dessus
            <span
              className="
                mx-2 
                font-extrabold"
            >plutôt 
            </span>
            que le
            <span
              className="
                mx-2 
                font-extrabold
                text-blue-400"
            >
              bleu 
            </span>
            ci-dessous s'il vous plaît. 
          </p>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <input 
            type="text" 
            name="floating_first_name" 
            id="floating_first_name" 
            className="
              block 
              py-2.5 
              px-0 
              w-full 
              text-xl  
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-600 
              text-white 
              focus:border-blue-500 
              focus:outline-none
              focus:ring-0
              peer" 
              placeholder=" " 
              required 
          />
          <label 
            htmlFor="floating_first_name" 
            className="
              peer-focus:font-medium 
              absolute 
              top-3 
              right-23 
              -z-10 
              origin-left 
              w-full 
              text-xl not-[]:
              text-gray-300 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6"
          >
            Prénom (a obligatoire)
          </label>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <input 
            type="text" 
            name="floating_last_name" 
            id="floating_last_name" 
            className="
              block 
              py-2.5 
              px-0 
              w-full 
              text-xl 
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-600 
              text-white 
              focus:border-blue-500 
              focus:outline-none 
              focus:ring-0 
              peer" 
            placeholder=" " 
            required 
          />
          <label 
            htmlFor="floating_last_name" 
            className="
              peer-focus:font-medium 
              absolute 
              top-3 
              right-27 
              -z-10 
              origin-left 
              w-full 
              text-xl 
              text-gray-300 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6"
          >
            Nom (a obligatoire)
          </label>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <input 
            type="tel" 
            pattern="+33 [1-9]{1} [0-9]{2} [0-9]{2} [0-9]{2} [0-9]{2}" 
            name="floating_phone" 
            id="floating_phone" 
            className="
              block 
              py-2.5 
              px-0 
              w-full 
              text-xl 
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-600 
              text-white 
              focus:border-blue-500 
              focus:outline-none 
              focus:ring-0 
              peer" 
              placeholder=" " 
            />
          <label 
            htmlFor="floating_phone" 
            className="
              peer-focus:font-medium 
              absolute 
              top-3 
              right-12
              -z-10 
              origin-left 
              w-full 
              text-xl 
              text-gray-300 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6
              "
          >
            téléphone (+33 1 23 45 67 89)
          </label>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <input 
            type="text" 
            name="floating_company" 
            id="floating_company" 
            className="
              block 
              py-2.5 
              px-0 
              w-full 
              text-xl 
              bg-transparent 
              border-0 
              border-b-2 
              border-gray-600 
              text-white 
              focus:border-blue-500 
              focus:outline-none 
              focus:ring-0 
              peer" 
            placeholder=" "
          />
          <label 
            htmlFor="floating_company" 
            className="
              peer-focus:font-medium 
              absolute 
              top-3 
              right-45 
              -z-10 
              origin-left 
              w-full 
              text-xl 
              text-gray-300 
              duration-300 
              transform 
              -translate-y-6 
              scale-75 
              peer-focus:start-0 
              rtl:peer-focus:translate-x-1/4 
              peer-focus:text-blue-600 
              peer-focus:dark:text-blue-500 
              peer-placeholder-shown:scale-100 
              peer-placeholder-shown:translate-y-0 
              peer-focus:scale-75 
              peer-focus:-translate-y-6"
          >
            Société
          </label>
        </div>
        <div 
          className="
            relative 
            z-0 
            w-full 
            mb-5 
            group"
        >
          <label 
            htmlFor="message" 
            className="
              block 
              mb-2 
              text-xl 
              text-gray-300 
              font-medium"
          >
            Précisez votre besoin de site web s'il vous plaît
          </label>
          <textarea 
            id="message"
            value={value}
            onChange={handleChange} 
            className="
              block 
              p-2.5 
              min-h-24 
              w-full 
              text-xl 
              text-white 
              bg-gray-700 
              rounded-lg 
              border 
              border-gray-600 
              focus:ring-blue-500 
              focus:border-blue-500 
              placeholder-gray-400" 
              placeholder="contexte, public visé, fonctionnalités attendues..."
          >
          </textarea>
          <p 
            className="
              mt-2 
              text-sm 
              dark:text-red-400"
          >
            <span 
              className="font-medium"
            >Excusez-moi ne remplissez pas encore s'il vous plaît.
            </span>
              Veuillez cliquer sur le bouton orange ci-dessus plutôt que le bleu ci-dessous.
          </p>
        </div>
        <button 
          type="submit" 
          className="
            mt-2 
            px-5 
            py-2.5 
            w-full 
            text-2xl 
            text-center
            font-medium 
            text-gray-200
            bg-blue-600 
            hover:bg-blue-700 
            cursor-pointer 
            focus:ring-4 
            focus:outline-none 
            focus:ring-blue-800 
            rounded-lg 
            sm:w-auto"
        >
          Envoyer
        </button>
      </form>
}