import HeadFootLogos from '../containers/HeadFootLogos';

export default function Header() {
    return <header className='
        px-20 
        flex 
        justify-between
        items-center'
    >
        <HeadFootLogos />
        <nav className='
            py-8
            sticky 
            top-0 
            z-50 
            bg-slate-800 
            shadow-sm
            '
        >
            <ul className='
                flex
                flex-col
                md:flex-row 
                justify-between
            '>
                <li>   
                    <a 
                        href='#moi&vous=nous' 
                        className='
                            block 
                            px-4 
                            py-2 
                            text-blue-300 
                            hover:text-blue-600 
                            hover:scale-110 
                            transition 
                            duration-600 
                            motion-reduce:duration-3000 
                            ease-in-out 
                            '
                    >
                        nous
                    </a>
                </li>
                <li>
                     <a 
                        href='#competences'
                        className='
                            block 
                            px-4 
                            py-2 
                            text-blue-300
                            hover:text-blue-600
                            duration-600 
                            motion-reduce:duration-3000 
                            ease-in-out 
                            hover:scale-110'
                    >
                        compétences
                    </a>
                </li>
                <li>   
                    <a 
                        href='#projets'
                        className='
                            block 
                            px-4 
                            py-2 
                            text-blue-300
                            hover:text-blue-600
                            duration-600 
                            motion-reduce:duration-3000 
                            ease-in-out 
                            hover:scale-110'
                    >
                        projets
                    </a>
                </li>
                <li>   
                    <a 
                        href='#parcours'
                        className='
                            block 
                            px-4 
                            py-2 
                            text-blue-300
                            hover:text-blue-600
                            duration-600 
                            motion-reduce:duration-3000 
                            ease-in-out 
                            hover:scale-110'
                    >
                        parcours
                    </a>
                </li>
                <li>   
                    <a 
                        href='#contact'
                        className='
                            block 
                            px-4 
                            py-2 
                            text-blue-300
                            hover:text-blue-600
                            duration-600 
                            motion-reduce:duration-3000 
                            ease-in-out 
                            hover:scale-110'
                    >
                        contact
                    </a>
                </li>
            </ul>
        </nav>
    </header>
}