export default function Project(
    {
        URL, 
        URI, 
        label, 
        projectNumber
    }
    :{
        URL: string,
        URI: string, 
        label: string,
        projectNumber: number
    }
){
    return <article 
        className="
            m-8 
            bg-gray-900  
            block 
            max-w-sm 
            rounded-4xl 
            shadow-xs"
        >
            <a 
                href={URL}
                target="_blank" 
                aria-label={label}
            >
            <h4
            className="
                text-2xl
                leading-loose"
            >
                {projectNumber}
            </h4>
            <div 
                className="
                    p-6 
                    text-center"
            >
                <span 
                    className="
                        inline-flex 
                        items-center 
                        bg-brand-softer 
                        border 
                        border-brand-subtle 
                        text-fg-brand-strong 
                        text-xs 
                        font-medium 
                        px-1.5 
                        py-0.5 
                        rounded-sm"
                >
                    <img 
                        src={URI}
                        className='
                            lazy 
                            max-h-80
                            will-change-filter 
                            filter 
                            duration-300
                            hover:drop-shadow-[0_0_2em_#646cffaa]' 
                        alt={label}
                    />
                </span>
                <h5 
                    className="
                        m-6 
                        text-2xl 
                        leading-loose 
                        text-orange-500 
                        font-semibold 
                        tracking-tight 
                        text-heading"
                > 
                    {label}
                </h5>
            </div>
        </a>
    </article>
}